include:
  - board: nice_nano_v2
    shield: corne_l nice_oled
    snippet: studio-rpc-usb-uart
    artifact-name: corne_left
  - board: nice_nano_v2
    shield: corne_r nice_oled
    artifact-name: corne_right
