### periph
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL=y
CONFIG_NICE_OLED_WIDGET_STATIC_IMAGE_PERIPHERAL=n
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_CAT=n
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_GEM=n
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_HEAD=y
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_MS=100

CONFIG_NICE_OLED_WIDGET_PERIPHERAL=n

CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_POKEMON=n
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_SPACEMAN=n
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_SMART_BATTERY=n
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_WPM=n

CONFIG_NICE_OLED_WIDGET_STATIC_IMAGE_PERIPHERAL_VIM=n
CONFIG_NICE_OLED_WIDGET_STATIC_IMAGE_PERIPHERAL_VIP_MARCOS=n

### pos
CONFIG_NICE_OLED_WIDGET_OUTPUT_USB_CUSTOM_X=0
CONFIG_NICE_OLED_WIDGET_OUTPUT_USB_CUSTOM_Y=34
CONFIG_NICE_OLED_WIDGET_OUTPUT_BT_CUSTOM_X=8
CONFIG_NICE_OLED_WIDGET_OUTPUT_BT_CUSTOM_Y=32
CONFIG_NICE_OLED_WIDGET_OUTPUT_BT_UNBONDED_CUSTOM_X=-1
CONFIG_NICE_OLED_WIDGET_OUTPUT_BT_UNBONDED_CUSTOM_Y=32

CONFIG_NICE_OLED_WIDGET_BATTERY_CUSTOM_X=0
CONFIG_NICE_OLED_WIDGET_BATTERY_CUSTOM_Y=50

CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_CUSTOM_X=18
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_CUSTOM_Y=-18
