### central
CONFIG_NICE_OLED_WIDGET_WPM=y
CONFIG_NICE_OLED_WIDGET_WPM_NUMBER=y
CONFIG_NICE_OLED_WIDGET_WPM_SPEEDOMETER=y
CONFIG_NICE_OLED_WIDGET_WPM_GRAPH=n
CONFIG_NICE_OLED_WIDGET_WPM_LUNA=n
CONFIG_NICE_OLED_WIDGET_WPM_BONGO_CAT=n
CONFIG_NICE_OLED_WIDGET_WPM_GRAPH_FIXED_RANGE=y
CONFIG_NICE_OLED_WIDGET_WPM_GRAPH_FIXED_RANGE_MAX=100
CONFIG_NICE_OLED_WIDGET_RESPONSIVE=n

### HID
CONFIG_NICE_OLED_WIDGET_HID_INDICATORS=n

### raw HID
CONFIG_NICE_OLED_WIDGET_RAW_HID=n

### modifires
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS=n

### other widgets
CONFIG_NICE_OLED_WIDGET_LAYER=y
CONFIG_NICE_OLED_WIDGET_PROFILE_BIG=n
CONFIG_NICE_OLED_WIDGET_CENTRAL=n


### pos
CONFIG_NICE_OLED_WIDGET_OUTPUT_USB_CUSTOM_X=2
CONFIG_NICE_OLED_WIDGET_OUTPUT_USB_CUSTOM_Y=34
CONFIG_NICE_OLED_WIDGET_OUTPUT_BT_CUSTOM_X=2
CONFIG_NICE_OLED_WIDGET_OUTPUT_BT_CUSTOM_Y=32
CONFIG_NICE_OLED_WIDGET_OUTPUT_BT_UNBONDED_CUSTOM_X=2
CONFIG_NICE_OLED_WIDGET_OUTPUT_BT_UNBONDED_CUSTOM_Y=32

CONFIG_NICE_OLED_WIDGET_BATTERY_CUSTOM_X=0
CONFIG_NICE_OLED_WIDGET_BATTERY_CUSTOM_Y=50

CONFIG_NICE_OLED_WIDGET_WPM_GAUGE_CUSTOM_X=0
CONFIG_NICE_OLED_WIDGET_WPM_GAUGE_CUSTOM_Y=85
CONFIG_NICE_OLED_WIDGET_WPM_NEEDLE_CENTER_CUSTOM_X=16
CONFIG_NICE_OLED_WIDGET_WPM_NEEDLE_CENTER_CUSTOM_Y=110
CONFIG_NICE_OLED_WIDGET_WPM_LABEL_CUSTOM_X=8
CONFIG_NICE_OLED_WIDGET_WPM_LABEL_CUSTOM_Y=114

CONFIG_NICE_OLED_WIDGET_PROFILE_CUSTOM_X=0
CONFIG_NICE_OLED_WIDGET_PROFILE_CUSTOM_Y=137

CONFIG_NICE_OLED_WIDGET_LAYER_CUSTOM_X=0
CONFIG_NICE_OLED_WIDGET_LAYER_CUSTOM_Y=146

CONFIG_NICE_OLED_WIDGET_SLEEP_STATUS_CUSTOM_X=0
CONFIG_NICE_OLED_WIDGET_SLEEP_STATUS_CUSTOM_Y=0
